// Code generated by SQLBoiler 4.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Brands     string
	Categories string
	Customers  string
	OrderItems string
	Orders     string
	Products   string
	Staffs     string
	Stocks     string
	Stores     string
}{
	Brands:     "brands",
	Categories: "categories",
	Customers:  "customers",
	OrderItems: "order_items",
	Orders:     "orders",
	Products:   "products",
	Staffs:     "staffs",
	Stocks:     "stocks",
	Stores:     "stores",
}
