// Code generated by SQLBoiler 4.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("Brands", testBrandsUpsert)

	t.Run("Categories", testCategoriesUpsert)

	t.Run("Customers", testCustomersUpsert)

	t.Run("OrderItems", testOrderItemsUpsert)

	t.Run("Orders", testOrdersUpsert)

	t.Run("Products", testProductsUpsert)

	t.Run("Staffs", testStaffsUpsert)

	t.Run("Stocks", testStocksUpsert)

	t.Run("Stores", testStoresUpsert)
}
